karma/api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'api'

router = DefaultRouter()
router.register(r'karma', views.KarmaViewSet, basename='karma')
router.register(r'projects', views.ProjectViewSet, basename='projects')
router.register(r'highscore', views.HighscoreViewSet, basename='highscore')
urlpatterns = router.urls

urlpatterns += [
    path('auth/', obtain_auth_token),
]

karma/calibration/urls.py
from django.urls import path

from . import views

app_name = 'calibration'

urlpatterns = [
    path('', views.calibration, name='calibration'),
    path('data', views.calibration_data, name='calibration_data')
]

karma/karma/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='karma_index'),
    path('personal', personal_page, name='karma_personal'),
    path('add_project', add_project, name='karma_add_project'),
    path('add_categories', add_categories, name='karma_add_categories'),
    path('category/<int:category_id>', category_overview, name='karma_category_overview'),
    path('project/<int:project_id>', project_overview, name='karma_project_overview'),
    path('project_highscore/<int:project_id>/<int:nr_days>', project_highscore, name='karma_project_highscore'),
    path('project/<int:project_id>/<str:user_login>', project_user, name='karma_project_user'),
    path('api/project/<int:project_id>/active_count/days/<int:nr_days>', api_project_user_count, name='karma_api_project_user_count'),
    path('api/project/<int:project_id>/active_points/', api_project_activity_points, name='karma_api_project_activity_count'),
    path('personal/edit/<int:point_id>/', personal_page, name="edit_points"),
    path('project/rules/', karma_rules, name="karma_rules"),
]

karma/urls.py
"""karma URL Configuration"""
from django.contrib import admin
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('karma/', include('karma.karma.urls')),
    path('', lambda req: redirect('karma_index'), name='index'),
    path('api/', include('karma.api.urls')),
    path('calibration/', include('karma.calibration.urls')),
    path("auth/openid/", include("simple_openid_connect.integrations.django.urls")),
]

karma/karma/models.py
from django.contrib.auth.models import User, Group
from django.db import models
from django.conf import settings


class Project(models.Model):
    name = models.CharField(max_length=50, unique=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, blank=True, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    karma_rules = models.TextField(max_length=400, default='No special rules')

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        unique_together = ['name', 'project']
    name = models.CharField(max_length=50)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='categories')

    def __str__(self):
        return self.name


class KarmaPoints(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    time = models.DateTimeField()
    points = models.IntegerField()
    description = models.CharField(max_length=200)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

karma/calibration/forms.py
from django.forms import ModelForm

from karma.calibration.models import Calibration


class CalibrationForm(ModelForm):
    class Meta:
        model = Calibration
        fields = ('start_day', 'end_day', 'percent')

karma/api/views.py
from datetime import timedelta

from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q, Sum, F
from django.db.models.functions import TruncDate
from django.utils.timezone import now
from rest_framework import mixins, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.status import HTTP_400_BAD_REQUEST

from karma.api.serializers import KarmaSerializer, ProjectSerializer, HighscoreSerializer
from karma.karma.models import KarmaPoints, Project


class KarmaViewSet(viewsets.GenericViewSet,
                   mixins.CreateModelMixin,
                   mixins.ListModelMixin):
    serializer_class = KarmaSerializer

    def get_queryset(self):
        if 'project' in self.request.query_params:
            try:
                project = Project.objects.get(Q(name=self.request.query_params['project']) & (
                        Q(user=self.request.user) | Q(group__in=self.request.user.groups.all())))
            except ObjectDoesNotExist:
                return None
            return KarmaPoints.objects.filter(project=project)
        return KarmaPoints.objects.filter(Q(project__user=self.request.user) | Q(project__group__in=self.request.user.groups.all()))

    @action(detail=False)
    def by_day(self, request):
        """Group information by day and user"""
        queryset = self.get_queryset()
        if queryset:
            points = queryset.annotate(date=TruncDate('time'), username=F('user__username')).values('username', 'date').order_by('date').annotate(Sum('points'))
            return Response(points)
        return Response(status=404)


class ProjectViewSet(viewsets.GenericViewSet,
                     mixins.ListModelMixin):
    serializer_class = ProjectSerializer

    def get_queryset(self):
        return Project.objects.filter(Q(user=self.request.user) | Q(group__in=self.request.user.groups.all()))


class HighscoreViewSet(viewsets.GenericViewSet,
                       mixins.ListModelMixin):
    serializer_class = HighscoreSerializer

    def list(self, request, *args, **kwargs):
        try:
            project = Project.objects.get(Q(name=self.request.query_params['project']) & (
                    Q(user=self.request.user) | Q(group__in=self.request.user.groups.all())))
        except ObjectDoesNotExist:
            return Response({'project': ['Project does not exist']}, status=HTTP_400_BAD_REQUEST)
        days = self.request.query_params['days']
        try:
            days = int(days)
        except ValueError:
            return Response({'days': ['Days must be a number']})

        userpoints = KarmaPoints.objects. \
            filter(project=project, time__gte=now() - timedelta(days=days)). \
            values('user__username'). \
            annotate(points=Sum('points')). \
            order_by('-points')

        serializer = self.get_serializer(userpoints)
        return Response(serializer.data)

karma/calibration/views.py
from datetime import timedelta, date
import random
import statistics

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import render
from rest_framework.status import HTTP_400_BAD_REQUEST

from karma.karma.models import KarmaPoints, Project
from karma.calibration.forms import CalibrationForm
from karma.calibration.models import Calibration


@login_required
def calibration(request):
    if request.method == 'POST':
        form = CalibrationForm(request.POST)
        if form.is_valid():
            c = form.save(commit=False)
            c.user = request.user
            c.save()
            messages.success(request, 'Calibration submitted successfully')
        else:
            raise HttpResponseBadRequest()
    range_start = date.today() - timedelta(days=365)
    range_end = date.today()
    start = range_start + random.random() * (range_end - range_start)
    end = start + timedelta(days=7)
    project = Project.objects.get(id=settings.CALIBRATION_PROJECT)
    week_entries = KarmaPoints.objects. \
        filter(project=project, time__gte=start, time__lte=end + timedelta(days=1))
    week_points = week_entries. \
        values('user__username'). \
        annotate(points=Sum('points')).order_by('-points')
    week_persons = len(week_points)
    day_entries = KarmaPoints.objects. \
        filter(project=project, time__day=end.day, time__month=end.month, time__year=end.year)
    day_points = day_entries. \
        values('user__username'). \
        annotate(points=Sum('points')). \
        order_by('-points')
    day_persons = len(day_points)
    form = CalibrationForm({'start_day': start, 'end_day': end})
    return render(request, 'calibration/calibration.html', {
        'form': form,
        'week_points': week_points,
        'week_persons': week_persons,
        'week_entries': week_entries.count(),
        'week_sum': week_entries.aggregate(Sum('points'))['points__sum'] or 0,
        'day_points': day_points,
        'day_persons': day_persons,
        'day_entries': day_entries.count(),
        'day_sum': day_entries.aggregate(Sum('points'))['points__sum'] or 0,
        'start_day': start,
        'end_day': end,
    })

@login_required
def calibration_data(request):
    data = Calibration.objects.all()
    csv = ['week_points_sum,week_user_count,week_mean,week_median,week_stddev,day_points_sum,day_user_count,day_mean,day_median,day_stddev,calibration']
    for entry in data:
        start = entry.start_day
        end = entry.end_day
        project = Project.objects.get(id=settings.CALIBRATION_PROJECT)
        week_entries = KarmaPoints.objects. \
            filter(project=project, time__gte=start, time__lte=end + timedelta(days=1))
        week_points = week_entries. \
            values('user__username'). \
            annotate(points=Sum('points')).order_by('-points')
        week_points = [e['points'] for e in week_points]
        week_persons = len(week_points)
        if week_points:
            wmean = statistics.mean(week_points)
            wmedian = statistics.median(week_points)
            wpoints = sum(week_points)
        else:
            wmean = wmedian = wpoints = 0
        if len(week_points) > 1:
            wstdev = statistics.stdev(week_points)
        else:
            wstdev = 0

        day_entries = KarmaPoints.objects. \
            filter(project=project, time__day=end.day, time__month=end.month, time__year=end.year)
        day_points = day_entries. \
            values('user__username'). \
            annotate(points=Sum('points')). \
            order_by('-points')
        day_points = [e['points'] for e in day_points]
        day_persons = len(day_points)
        if day_points:
            dmean = statistics.mean(day_points)
            dmedian = statistics.median(day_points)
            dpoints = sum(day_points)
        else:
            dmean = dmedian = dpoints = 0
        if len(day_points) > 1:
            dstdev = statistics.stdev(day_points)
        else:
            dstdev = 0

        percentage = entry.percent / 100
        csv.append(','.join([str(x) for x in [wpoints, week_persons, wmean, wmedian, wstdev, dpoints, day_persons, dmean, dmedian, dstdev, percentage]]))
    return HttpResponse('\n'.join(csv), content_type='text/csv')

karma/karma/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponseForbidden
from django.shortcuts import redirect, get_object_or_404
from django.template.response import TemplateResponse
from datetime import timedelta
import math
from django.utils.timezone import now
from django.core.paginator import Paginator

from karma.karma.forms import KarmaPointsForm, KarmaProjectForm, KarmaCategoryForm
from karma.karma.models import KarmaPoints, Project, Category
from django.conf import settings


@login_required
def index(request):
    return redirect('karma_personal')


@login_required()
def personal_page(request, point_id=None):
    if point_id:
        point_object = get_object_or_404(KarmaPoints, pk=point_id, user=request.user)
    else:
        point_object = None
    if request.POST:
        form = KarmaPointsForm(request.POST, instance=point_object)
        if form.is_valid():
            point = form.save(commit=False)
            point.user = request.user
            point.save()
            return redirect('karma_personal')
    else:
        form = KarmaPointsForm(instance=point_object)

    return TemplateResponse(request, 'karma/personal.html', {
        'edit': point_id,
        'form': form,
        'points': KarmaPoints.objects.filter(user=request.user).order_by('-time'),
        'sum': KarmaPoints.objects.filter(user=request.user).aggregate(Sum('points'))['points__sum'],
        'projects': Project.objects.filter(Q(user=request.user) | Q(group__user=request.user)).distinct().order_by('name'),
        'categories': Category.objects.filter(Q(project__user=request.user) | Q(project__group__user=request.user)).distinct().order_by('name'),
    })

@login_required()
def add_project(request):
    if request.POST:
        form = KarmaProjectForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('karma_add_project')
    else:
        form = KarmaProjectForm()
    return TemplateResponse(request, 'karma/add_project.html', {
        'form': form,
        'projects': Project.objects.filter(Q(user=request.user) | Q(group__user=request.user)).distinct().order_by('name')
    })


@login_required()
def add_categories(request):
    if request.POST:
        form = KarmaCategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('karma_add_categories')
    else:
        form = KarmaCategoryForm()
    return TemplateResponse(request, 'karma/add_category.html', {
        'form': form,
        'categories': Category.objects.filter(Q(project__user=request.user)| Q(project__group__user=request.user)).distinct().order_by('name')
    })


@login_required()
def project_overview(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if not Project.objects.filter(pk=project_id).filter(Q(user=request.user) | Q(group__user=request.user)):
        raise HttpResponseForbidden()

    items = KarmaPoints.objects.filter(project=project).order_by('-time')

    page = request.GET.get('page')
    paginator = Paginator(items, settings.ITEMS_PER_PAGE)
    displayedItems = paginator.get_page(page)

    return TemplateResponse(request, 'karma/project_overview.html', {
        'project': project,
        'sum': KarmaPoints.objects.filter(project=project).aggregate(Sum('points'))['points__sum'],
        'points': displayedItems
    })

@login_required()
def category_overview(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    return TemplateResponse(request, 'karma/category_overview.html', {
        'category': category,
        'sum': KarmaPoints.objects.filter(category=category).aggregate(Sum('points'))['points__sum'],
        'points': KarmaPoints.objects.filter(category=category).order_by('-time')
    })


@login_required()
def project_user(request, project_id, user_login):
    project = get_object_or_404(Project, pk=project_id)
    user = get_object_or_404(User, username=user_login)
    if not Project.objects.filter(pk=project_id).filter(Q(user=request.user) | Q(group__user=request.user)):
        raise HttpResponseForbidden()
    return TemplateResponse(request, 'karma/project_user.html', {
        'project': project,
        'user': user,
        'sum': KarmaPoints.objects.filter(project=project, user=user).aggregate(Sum('points'))['points__sum'],
        'points': KarmaPoints.objects.filter(project=project, user=user).order_by('-time')
    })


@login_required()
def project_highscore(request, project_id, nr_days):
    project = get_object_or_404(Project, pk=project_id)
    if not Project.objects.filter(pk=project_id).filter(Q(user=request.user) | Q(group__user=request.user)):
        raise HttpResponseForbidden()

    if int(nr_days) > 100000:
        nr_days = '100000'

    userpoints = KarmaPoints.objects.\
        filter(project=project, time__gte=now()-timedelta(days=int(nr_days))).\
        values('user__username').\
        annotate(points=Sum('points')).\
        order_by('-points')

    return TemplateResponse(request, 'karma/project_highscore.html', {
        'days': nr_days,
        'project': project,
        'users': userpoints,
    })


def api_project_user_count(request, project_id, nr_days):
    project = get_object_or_404(Project, pk=project_id)

    usercount = KarmaPoints.objects.\
        filter(project=project, time__gte=now()-timedelta(days=int(nr_days))).values('user').distinct().count()
    return TemplateResponse(request, 'karma/api_project_active', {
        'count': usercount,
    })


def api_project_activity_points(request, project_id):
    project = get_object_or_404(Project, pk=project_id)

    userpoints_week = KarmaPoints.objects.\
        filter(project=project, time__gte=now()-timedelta(days=7)).\
        aggregate(week_sum=Sum('points'))['week_sum']

    # Full karma is a full work week of one person
    activepoints = userpoints_week / 2400

    # Scale (8000 = karma bar is full)
    activepoints *= 8000

    # Return integer
    activepoints = int(activepoints)
    return TemplateResponse(request, 'karma/api_project_active', {
        'count': activepoints,
    })


@login_required()
def karma_rules(request):
    return TemplateResponse(request, 'karma/rules.html', {
        'projects': Project.objects.filter(Q(user=request.user) | Q(group__user=request.user)).distinct().order_by('name'),
    })

karma/karma/templates/karma/add_category.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
Add Category
{% endblock %}

{% block content %}

    <form action="{% url 'karma_add_categories' %}" method="POST">
    {% csrf_token %}
        Name of Category: {{ form.name }}
        In Project: {{ form.project }}

    <input type="submit" name="submit" value="Submit">
    </form>


    <table>
        <th>Bestehende Kategorien:</th>
    {% for cat in categories %}
        <tr>
            <td><a href="{% url 'karma_category_overview' cat.pk %}">{{ cat.name }}</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

karma/karma/templates/karma/add_project.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
Add Project
{% endblock %}

{% block content %}

    <h3>Create a new project:</h3>
    <form action="{% url 'karma_add_project' %}" method="POST">
        {% csrf_token %}
        Name of Project: {{ form.name }} <br>
        Owner: {{ form.user }} <br>
        Group allowed to contribute: {{ form.group }} <br>
        Karma rules: <br>
        {{ form.karma_rules }} <br>
        <input type="submit" name="submit" value="Submit">
    </form>


    <h3>Your Projects:</h3>
    <table>
    {% for project in projects %}
        <tr>
            <td><a href="{% url 'karma_project_overview' project.pk %}">{{ project.name }}</a></td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

karma/karma/templates/karma/category_overview.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{{ category.name }}
{% endblock %}

{% block content %}

    <a href="{% url 'karma_add_project' %}">Add Project</a> | <a href="{% url 'karma_project_highscore' category.project.pk 45 %}">Highscore</a>

    <h1>Overview for Category {{ category.name }}</h1>

    <div>
        <table>
            <tr>
                <th width="170em">Wann</th>
                <th>Wieviel?</th>
                <th>Wer?</th>
                <th>Was?</th>
                <th>Projekt</th>
            </tr>
            <tr>
                <th>Summe:</th>
                <th>{{ sum }}</th>
                <th></th>
            </tr>
            {% for point in points %}
                <tr>
                    <td style="">{{ point.time }}</td>
                    <td>{{ point.points }}</td>
                    <td>{{ point.user.username }}</td>
                    <td>{{ point.description }}</td>
                    <td><a href="{% url 'karma_project_overview' point.project.pk %}">{{ point.project }}</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

karma/karma/templates/karma/personal.html
{% extends "base.html" %}
{% load i18n %}
{% load widget_tweaks %}

{% block head %}
{{ block.super }}

    {{ form.media }}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script type="text/javascript">
    var categories = [
        {% for category in categories %}
            { text: "{{ category.name }}", value: {{ category.pk }}, project: {{ category.project.pk }} },
        {% endfor %}
    ];
    </script>
{% endblock %}

{% block title %}
{% if edit %}
Edit Entry
{% else %}
Personal Page
{% endif %}
{% endblock %}

{% block content %}

    My projects: {% for project in projects %}<a href="{% url 'karma_project_overview' project.pk %}">{{ project.name }}</a> (<a href="{% url 'karma_project_highscore' project.pk 45 %}">Highscore</a>)&emsp;{% endfor %}


    {% if edit %}
        <h1>Edit Entry</h1>
        <a href="{% url "karma_personal" %}">New entry</a>
    {% else %}
        <h1>Personal Page</h1>
    {% endif %}

    <div class="wrap form-group">
        <form action="{% if edit %}{% url 'edit_points' edit %}{% else %}{% url 'karma_personal' %}{% endif %}" method="post">
            {% csrf_token %}
            <label for="id_points">Points (refer to the <a href="{% url 'karma_rules' %}" target="_blank">rules of the project</a>) : </label><input id="id_points" class="form-control" style="width: 7em"
                                                          type="number" name="{{ form.points.name }}"
                                                          value="{{ form.points.value }}" placeholder="Points"
                                                          required="required" autofocus="autofocus"/>
            {% if form.points.errors %}
                <ul class="alert alert-danger">{{ form.points.errors }}</ul>
            {% endif %}
            <label for="id_desc">Description:</label>
            <input class="form-control" id="id_desc" type="text" name="{{ form.description.name }}"
                   value="{{ form.description.value|default_if_none:'' }}" placeholder="What have you done?"
                   required="required" width="50em"/>
            {% if form.description.errors %}
                <ul class="alert alert-danger">{{ form.description.errors }}</ul>{% endif %}
            <label for=":id_project">Project:</label>  <a href="{% url 'karma_add_project' %}">Add Project</a>
            <select class="form-control" name="{{ form.project.name }}" id="project_selector">
                <option value="">--------</option>
                {% for project in projects %}
                    <option {% if form.project.value == project.pk %}selected{% endif %} value="{{ project.pk }}">{{ project.name }}</option>
                {% endfor %}
            </select>
            <br />
            <label for=":id_category">Category:</label>  <a href="{% url 'karma_add_categories' %}">Add Category</a>
            <select class="form-control" name="{{ form.category.name }}" id="category_selector">
                <option value="">--------</option>
                {% for category in categories %}
                    <option {% if form.category.value == category.pk %}selected{% endif %} value="{{ category.pk }}">{{ category.name }}</option>
                {% endfor %}
            </select>
        <br />
            <label for="datetime">Date:</label><br>
            {% render_field form.time class+="form-control" id="datetimepicker" %}
        <br />
            <input type="submit" name="submit" value="{% if edit %}Edit{% else %}Submit{% endif %}" class="btn btn-default"/>
        </form>
    </div>

    <div>
        <table>
            <tr>
                <th width="170em">Wann</th>
                <th>Wieviel?</th>
                <th>Was?</th>
                <th>Project</th>
                <th>Category</th>
            </tr>
            <tr>
                <th>Summe:</th>
                <th>{{ sum }}</th>
                <th></th>
            </tr>
            {% for point in points %}
                <tr>
                    <td style="">{{ point.time }}</td>
                    <td>{{ point.points }}</td>
                    <td>{{ point.description }}</td>
                    <td><a href="{% url 'karma_project_overview' point.project.pk %}">{{ point.project }}</a></td>
                    <td><a href="{% url 'karma_category_overview' point.category.pk %}">{{ point.category }}</a></td>
                    <td><a href="{% url 'edit_points' point.pk %}" class="btn btn-default"><i class="fa fa-pencil"></i> </a> </td>
                </tr>
            {% endfor %}
        </table>
    </div>

    <a href="{% url 'karma_add_categories' %}">Add Category</a> -
    <a href="{% url 'karma_add_project' %}">Add Project</a>

{% endblock %}

karma/karma/templates/karma/project_highscore.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
Highscore {{ project.name }}
{% endblock %}


{% block content %}

    <a href="{% url 'karma_add_project' %}">Add Project</a>

    <h1>Highscore for Project {{ project.name }} ({{ days }} days)</h1>

    <div>
        <table>
            {% for user in users %}
                <tr>
                    <td>{{ user.user__username }}</td>
                    <td>{{ user.points }}</td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

karma/karma/templates/karma/project_overview.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{{ project.name }}
{% endblock %}


{% block content %}

    <a href="{% url 'karma_add_project' %}">Add Project</a> | <a href="{% url 'karma_project_highscore' project.pk 45 %}">Highscore</a>

    <h1>Overview for Project {{ project.name }}</h1>

    <div>
        <table>
            <tr>
                <th width="170em">Wann</th>
                <th>Wieviel?</th>
                <th>Wer?</th>
                <th>Was?</th>
                <th>Category</th>
            </tr>
            <tr>
                <th>Summe:</th>
                <th>{{ sum }}</th>
                <th></th>
            </tr>
            {% for point in points %}
                <tr>
                    <td style="">{{ point.time }}</td>
                    <td>{{ point.points }}</td>
                    <td><a href="{% url 'karma_project_user' project.pk point.user.username %}">{{ point.user.username }}</a></td>
                    <td>{{ point.description }}</td>
                    <td><a href="{% url 'karma_category_overview' point.category.pk %}">{{ point.category }}</a></td>
                </tr>
            {% endfor %}
        </table>
        <div class="pagination">
            <span class="step-links">
                <div class="btn-group" role="group" aria-label="btn-group">
                    {% if points.has_previous %}
                        <a class="btn btn-default" href="?page=1">&laquo; first</a>
                        <a class="btn btn-default" href="?page={{ points.previous_page_number }}">previous</a>
                    {% endif %}
                    {% if points.has_other_pages %}
                        <span class="current btn btn-default">
                            Page {{ points.number }} of {{ points.paginator.num_pages }}
                        </span>
                    {% endif %}
                    {% if points.has_next %}
                        <a class="btn btn-default" href="?page={{ points.next_page_number }}">next</a>
                        <a class="btn btn-default" href="?page={{ points.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </div>
            </span>
        </div>
    </div>

{% endblock %}

karma/karma/templates/karma/project_user.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
{{ user.username }} in {{ project.name }}
{% endblock %}


{% block content %}

    <a href="{% url 'karma_add_project' %}">Add Project</a>

    <h1>Overview for User <b>{{ user.username }}</b> in Project <b>{{ project.name }}</b></h1>

    <div>
        <table>
            <tr>
                <th width="170em">Wann</th>
                <th>Wieviel?</th>
                <th>Was?</th>
                <th>Category</th>
            </tr>
            <tr>
                <th>Summe:</th>
                <th>{{ sum }}</th>
                <th></th>
            </tr>
            {% for point in points %}
                <tr>
                    <td style="">{{ point.time }}</td>
                    <td>{{ point.points }}</td>
                    <td>{{ point.description }}</td>
                    <td><a href="{% url 'karma_category_overview' point.category.pk %}">{{ point.category }}</a></td>
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}

karma/karma/templates/karma/rules.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}
Karma Rules
{% endblock %}


{% block content %}

    <h1>Karma Rules</h1>

    <div>
        {% for project in projects %}
            <h3>{{ project.name }}</h3>
            {{ project.karma_rules }}
        {% endfor %}

    </div>

{% endblock %}

karma/karma/templates/karma/score_list.html
<div class="score">
    Bla
</div>