karma/calibration/urls.py
from django.urls import path

from . import views

app_name = 'calibration'

urlpatterns = [
    path('', views.calibration, name='calibration'),
    path('data', views.calibration_data, name='calibration_data')
]

karma/urls.py
"""karma URL Configuration"""
from django.contrib import admin
from django.shortcuts import redirect
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('karma/', include('karma.karma.urls')),
    path('', lambda req: redirect('karma_index'), name='index'),
    path('api/', include('karma.api.urls')),
    path('calibration/', include('karma.calibration.urls')),
    path("auth/openid/", include("simple_openid_connect.integrations.django.urls")),
]

karma/calibration/models.py
from django.conf import settings
from django.db import models


class Calibration(models.Model):
    start_day = models.DateField()
    end_day = models.DateField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    percent = models.IntegerField()

karma/calibration/forms.py
from django.forms import ModelForm

from karma.calibration.models import Calibration


class CalibrationForm(ModelForm):
    class Meta:
        model = Calibration
        fields = ('start_day', 'end_day', 'percent')

karma/calibration/views.py
from datetime import timedelta, date
import random
import statistics

from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import HttpResponseBadRequest, HttpResponse
from django.shortcuts import render
from rest_framework.status import HTTP_400_BAD_REQUEST

from karma.karma.models import KarmaPoints, Project
from karma.calibration.forms import CalibrationForm
from karma.calibration.models import Calibration


@login_required
def calibration(request):
    if request.method == 'POST':
        form = CalibrationForm(request.POST)
        if form.is_valid():
            c = form.save(commit=False)
            c.user = request.user
            c.save()
            messages.success(request, 'Calibration submitted successfully')
        else:
            raise HttpResponseBadRequest()
    range_start = date.today() - timedelta(days=365)
    range_end = date.today()
    start = range_start + random.random() * (range_end - range_start)
    end = start + timedelta(days=7)
    project = Project.objects.get(id=settings.CALIBRATION_PROJECT)
    week_entries = KarmaPoints.objects. \
        filter(project=project, time__gte=start, time__lte=end + timedelta(days=1))
    week_points = week_entries. \
        values('user__username'). \
        annotate(points=Sum('points')).order_by('-points')
    week_persons = len(week_points)
    day_entries = KarmaPoints.objects. \
        filter(project=project, time__day=end.day, time__month=end.month, time__year=end.year)
    day_points = day_entries. \
        values('user__username'). \
        annotate(points=Sum('points')). \
        order_by('-points')
    day_persons = len(day_points)
    form = CalibrationForm({'start_day': start, 'end_day': end})
    return render(request, 'calibration/calibration.html', {
        'form': form,
        'week_points': week_points,
        'week_persons': week_persons,
        'week_entries': week_entries.count(),
        'week_sum': week_entries.aggregate(Sum('points'))['points__sum'] or 0,
        'day_points': day_points,
        'day_persons': day_persons,
        'day_entries': day_entries.count(),
        'day_sum': day_entries.aggregate(Sum('points'))['points__sum'] or 0,
        'start_day': start,
        'end_day': end,
    })

@login_required
def calibration_data(request):
    data = Calibration.objects.all()
    csv = ['week_points_sum,week_user_count,week_mean,week_median,week_stddev,day_points_sum,day_user_count,day_mean,day_median,day_stddev,calibration']
    for entry in data:
        start = entry.start_day
        end = entry.end_day
        project = Project.objects.get(id=settings.CALIBRATION_PROJECT)
        week_entries = KarmaPoints.objects. \
            filter(project=project, time__gte=start, time__lte=end + timedelta(days=1))
        week_points = week_entries. \
            values('user__username'). \
            annotate(points=Sum('points')).order_by('-points')
        week_points = [e['points'] for e in week_points]
        week_persons = len(week_points)
        if week_points:
            wmean = statistics.mean(week_points)
            wmedian = statistics.median(week_points)
            wpoints = sum(week_points)
        else:
            wmean = wmedian = wpoints = 0
        if len(week_points) > 1:
            wstdev = statistics.stdev(week_points)
        else:
            wstdev = 0

        day_entries = KarmaPoints.objects. \
            filter(project=project, time__day=end.day, time__month=end.month, time__year=end.year)
        day_points = day_entries. \
            values('user__username'). \
            annotate(points=Sum('points')). \
            order_by('-points')
        day_points = [e['points'] for e in day_points]
        day_persons = len(day_points)
        if day_points:
            dmean = statistics.mean(day_points)
            dmedian = statistics.median(day_points)
            dpoints = sum(day_points)
        else:
            dmean = dmedian = dpoints = 0
        if len(day_points) > 1:
            dstdev = statistics.stdev(day_points)
        else:
            dstdev = 0

        percentage = entry.percent / 100
        csv.append(','.join([str(x) for x in [wpoints, week_persons, wmean, wmedian, wstdev, dpoints, day_persons, dmean, dmedian, dstdev, percentage]]))
    return HttpResponse('\n'.join(csv), content_type='text/csv')

karma/calibration/templates/calibration/calibration.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}
Vote
{% endblock %}
{% block head %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
{% endblock %}
{% block content %}
    <section class="section">
        <div class="container">
            <h1>Calibration</h1>
            <p>To calibrate the Karmaleiste™, calibrations are needed to link karma points to activity in
                percent. <a href="{% url 'calibration:calibration_data' %}">Download data</a></p>
            <div class="col-md-6 col-sm-12">
                <h2>The week <small>{{ start_day|date:"d.m.y" }} &ndash; {{ end_day|date:"d.m.y" }}</small></h2>
                <h4 class="well-sm">{{ week_entries }} {% if week_entries == 1 %}entry{% else %}entries{% endif %} by {{ week_persons }}
                    {% if week_persons == 1 %}person{% else %}persons{% endif %}: {{ week_sum }} {% if day_sum == 1 %}
                        point{% else %}points{% endif %}</h4>
                <ul>
                    {% for point in week_points %}
                        <li>{{ point.user__username }}: {{ point.points }}</li>
                        {% empty %}
                        <li>No points in this week</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-6 col-sm-12">
                <h2>Current day <small>{{ end_day|date:"d.m.y" }}</small></h2>
                <h4 class="well-sm">{{ day_entries }} {% if day_entries == 1 %}entry{% else %}entries{% endif %} by {{ day_persons }}
                    {% if day_persons %}person{% else %}persons{% endif %}: {{ day_sum }} {% if day_sum == 1 %}
                        point{% else %}points{% endif %}</h4>
                <ul>
                    {% for point in day_points %}
                        <li>{{ point.user__username }}: {{ point.points }}</li>
                        {% empty %}
                        <li>No points this day</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <form method="POST" action="{% url 'calibration:calibration' %}" class="form col-md-6 col-sm-12"
              style="margin-top:20px">
            <div style="display: none">{% csrf_token %}</div>
            {{ form.start_day|attr:"type:hidden" }}
            {{ form.end_day|attr:"type:hidden" }}
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">Activity</span>
                    {{ form.percent|attr:"min:0"|attr:"max:100"|add_class:"form-control"|attr:"autofocus:true" }}
                    <span class="input-group-addon">%</span>
                </div>
            </div>
            <button type="submit" class="form-control btn btn-primary">Submit</button>
        </form>
    </section>
{% endblock %}